site:
  about:
    siteName: Jacquard SDK
    siteDescription: This is a short description of this project.
Editorial:
  primaryColor: '#DE9149'
  social:
    github: 'username/project' # TODO Link with github
  extraCss:
    - 'assets/css/jacquard.scss'
  extraJs:
    - 'assets/js/jacquard.js'
  assets:
    sourceDirs: 
      - 'assets/media'
  metaComponents:
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Getting Started'
    - type: 'wiki'
      itemId: 'wiki'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
javadoc:
   sourceDirs:
     - './../../../../sdk/sdk/src/main/java'